const imageurls = {
    "back_ground": "images/back_ground.png",
    "main_body": "images/main_body.png",
    "tbl4_kid_0": "images/search_bar.png",
    "tbl4_kid_1": "images/search_bar.png",
    "tbl4_kid_2": "images/search_bar.png",
    "tbl4_kid_3": "images/search_bar.png",
    "tbl4_kid_4": "images/search_bar.png",
    "tbl4_kid_5": "images/search_bar.png",
    "tbl4_kid_6": "images/search_bar.png",
    "tbl4_kid_7": "images/search_bar.png",
    "tbl4_kid_0_kid_1": "images/table_0.jpg",
    "tbl4_kid_1_kid_1": "images/table_1.jpg",
    "tbl4_kid_2_kid_1": "images/table_2.jpg",
    "tbl4_kid_3_kid_1": "images/table_3.jpg",
    "tbl4_kid_4_kid_1": "images/table_4.jpg",
    "tbl4_kid_5_kid_1": "images/table_5.jpg",
    "tbl4_kid_6_kid_1": "images/table_6.jpg",
    "tbl4_kid_7_kid_1": "images/table_7.jpg",
    "bottom": "images/bottom.png",
    "search": "images/search.png",
    "search_bar": "images/search_bar.png",
    "icon": "images/icon.png",
    "search_go": "images/search_go.png",
    "Basket": "images/baskect.png",
    "Help": "images/help.png",
    "your_account": "images/accounts.png",
    "alexa": "images/alexa.png",
    "shop": "images/shop.png",
    "icon2": "images/icon2.png",

};

const texts = {
    "tbl4_kid_0_kid_0": "Amazon Basics",
    "tbl4_kid_1_kid_0": "School",
    "tbl4_kid_2_kid_0": "Fashion For All",
    "tbl4_kid_3_kid_0": "Kitchen",
    "tbl4_kid_4_kid_0": "Sports",
    "tbl4_kid_5_kid_0": "Learning",
    "tbl4_kid_6_kid_0": "Home ",
    "tbl4_kid_7_kid_0": "Toys",

    "tbl4_kid_0_kid_2": "Show Now",
    "tbl4_kid_1_kid_2": "Show Now",
    "tbl4_kid_2_kid_2": "Show Now",
    "tbl4_kid_3_kid_2": "Show Now",
    "tbl4_kid_4_kid_2": "Show Now",
    "tbl4_kid_5_kid_2": "Show Now",
    "tbl4_kid_6_kid_2": "Show Now",
    "tbl4_kid_7_kid_2": "Show Now",
};