const imageurls = {
"app_0_pic":"images/a0.png",
"app_1_pic":"images/a1.png",
"app_2_pic":"images/a2.png",
"app_3_pic":"images/a3.png",
"app_4_pic":"images/a4.png",
"app_5_pic":"images/a5.png",
"app_6_pic":"images/a6.png",
"app_7_pic":"images/a7.png",
"app_8_pic":"images/a8.png",
"app_9_pic":"images/a9.png",

"game_0_pic":"images/g0.png",
"game_1_pic":"images/g1.png",
"game_2_pic":"images/g2.png",
"game_3_pic":"images/g3.png",
"game_4_pic":"images/g4.png",
"game_5_pic":"images/g5.png",
"game_6_pic":"images/g6.png",
"game_7_pic":"images/g7.png",
"game_8_pic":"images/g8.png",
"game_9_pic":"images/g9.png",


"p0":"images/p0.png",
"p1":"images/p1.png",
"p2":"images/p2.png",

"tbl_0":"images/m0.png",
"tbl_1":"images/m1.png",
"tbl_2":"images/m2.png",
"tbl_3":"images/m3.png",
"tbl_4":"images/m4.png",
"tbl_5":"images/m5.png",
"tbl_6":"images/m6.png",
"tbl_7":"images/m7.png",
"tbl_8":"images/m8.png",
"tbl_9":"images/m9.png",
"tbl_10":"images/m10.png",
"tbl_11":"images/m11.png",

"search_go":"images/search_go.png",



"division_pic":"images/division.png",
"rank_pic":"images/rank.png",
"fast_pic":"images/fast.png",
"park_pic":"images/garden.png",
"edu_pic":"images/edu.png",

};

const texts = {
"homepage":["首页","30px"],
"app_title_kid_1":["更多>","18px"],
"game_title_kid_1":["更多>","18px"],
"app_title_kid_0":["精品应用","20px"],
"game_title_kid_0":["精品游戏","20px"],
"division_name":["分类"],
"fast_name":["快应用"],
"park_name":["小华"],
"edu_name":["教育"],
"rank_name":["排名"],
"app_0_word":["touch下"],
"app_1_word":["笔记"],
"app_2_word":["游端"],
"app_3_word":["备忘录"],
"app_4_word":["相册"],
"app_5_word":["视频"],
"app_6_word":["日历"],
"app_7_word":["Snap"],
"app_8_word":["相机"],
"app_9_word":["画册"],
"app_0_install":["安装"],
"app_1_install":["安装"],
"app_2_install":["安装"],
"app_3_install":["安装"],
"app_4_install":["安装"],
"app_5_install":["安装"],
"app_6_install":["安装"],
"app_7_install":["安装"],
"app_8_install":["安装"],
"app_9_install":["安装"],
"game_0_word":["漫威"],
"game_1_word":["如意金箍"],
"game_2_word":["神龙呼唤"],
"game_3_word":["梦中穿梭"],
"game_4_word":["愤怒小鸟"],
"game_5_word":["原神"],
"game_6_word":["卧虎藏龙"],
"game_7_word":["点点能量"],
"game_8_word":["你的星星"],
"game_9_word":["虎虎生威"],
"game_0_install":["安装"],
"game_1_install":["安装"],
"game_2_install":["安装"],
"game_3_install":["安装"],
"game_4_install":["安装"],
"game_5_install":["安装"],
"game_6_install":["安装"],
"game_7_install":["安装"],
"game_8_install":["安装"],
"game_9_install":["安装"],
};

const bords = {
    "search_bar": "1px",
};
const abs_pos = {

    "down_holder": [,],
    "mine": ["images/mine.png"],
    "home": ["images/home.png"],
    "shop": ["images/shop.png"],
    "new": ["images/new.png"],
    "add": ["images/game.png"],
    "mine_name": [, "我的"],
    "home_name": [, "主页"],
    "shop_name": [, "购物"],
    "new_name": [, "动态"],
    "add_name": [, "游戏"],
};