const imageurls = {
    "title": "images/blue.png",
    "title_kid_0": "images/t1.png",
    "title_kid_1": "images/t2.png",
    "title_kid_2": "images/t3.png",
    "title_kid_3": "images/t4.png",
    "title_kid_4": "images/t5.png",
    "title_kid_5": "images/t6.png",
    "title_kid_6": "images/t7.png",
    "title_kid_7": "images/t8.png",
    "title_kid_8": "images/t9.png",

    "wide_title_right_kid_0": "images/w1.png",
    "wide_title_right_kid_1": "images/w2.png",
    "wide_title_right_kid_2": "images/w3.png",

    "wide_title_left_kid_0": "images/l1.png",
    "wide_title_left_kid_2": "images/l2.png",

    "add_icon_1": "images/add_icon_1.png",
    "add_icon_2": "images/add_icon_2.png",
    "code": "images/code.png",

    "title_icons_kid_0": "images/tag_short.png",
    "title_icons_kid_1": "images/add_icon_2.png",
    "title_icons_kid_2": "images/branch_short.png",
    "public_repo": "images/public_repo.png",

    "photo_flow_kid_0": "images/p0.png",
    "photo_flow_kid_1": "images/p1.png",
    "photo_flow_kid_2": "images/p2.png",
    "photo_flow_kid_3": "images/p3.png",
    "photo_flow_kid_4": "images/p4.png",
    "photo_flow_kid_5": "images/p5.png",
    "photo_flow_kid_6": "images/p6.png",
    "photo_flow_kid_7": "images/p7.png",
    "photo_flow_kid_8": "images/p8.png",
    "photo_flow_kid_9": "images/p9.png",
    "photo_flow_kid_10": "images/p10.png",
    "photo_flow_kid_11": "images/p11.png",
    "photo_flow_kid_12": "images/p12.png",
    "photo_flow_kid_13": "images/p13.png",


    "language_names_kid_0": "images/la0.png",
    "language_names_kid_1": "images/la1.png",
    "language_names_kid_2": "images/la2.png",
    "language_names_kid_3": "images/la3.png",
    "language_names_kid_4": "images/la4.png",
    "language_names_kid_5": "images/la5.png",
    "language_names_kid_6": "images/la6.png",


    "language_bar": "images/language.png",

    "z3_1": "images/z3_1.png",
    "readme_write": "images/read1.png",
    "readme_less": "images/read2.png",
    "License": "images/license.png",
    "ReadMe": "images/readme.png",

    "tag_long": "images/tag_long.png",
    "branch_long": "images/branch_long.png",
    "master": "images/master.png",
    "go_to_file_1_kid_0": "images/search_go.png",
    "go_to_file_2": "images/search_go.png",
    "tag_short": "images/tag_short.png",
    "branch_short": "images/branch_short.png",

};

const texts = {
    "wide_title_left_kid_1": "Z3",
    "contributors": "Contributors",
    "add_contributors": "+269 contributors",
    "languages": "Languages",

    "main_left_body_kid_0_kid_0": "src",
    "main_left_body_kid_1_kid_0": "doc",
    "main_left_body_kid_2_kid_0": "main",
    "main_left_body_kid_3_kid_0": "cmake",
    "main_left_body_kid_4_kid_0": "docker",
    "main_left_body_kid_5_kid_0": "noarch",
    "main_left_body_kid_6_kid_0": "script",
    "main_left_body_kid_7_kid_0": "resource",
    "main_left_body_kid_8_kid_0": "git",
    "main_left_body_kid_9_kid_0": "gitignore",

    "main_left_body_kid_0_kid_1": "Bump docker/build-push-action from 6.4.0 ",
    "main_left_body_kid_1_kid_1": "Merge shared parts from polysat b",
    "main_left_body_kid_2_kid_1": "tiny fix to qprofdiff ",
    "main_left_body_kid_3_kid_1": "cmake: Use FindPython3",
    "main_left_body_kid_4_kid_1": "Update docker-image.yml (#5739)",
    "main_left_body_kid_5_kid_1": "fix generic example",
    "main_left_body_kid_6_kid_1": "follow instructions from #1879",
    "main_left_body_kid_7_kid_1": "Publishing SNK file private key for reproducible builds",
    "main_left_body_kid_8_kid_1": "disable publish and signing",
    "main_left_body_kid_9_kid_1": "Added pretty printing to python (#7320)",

    "main_left_body_kid_0_kid_2": "6 months ago",
    "main_left_body_kid_1_kid_2": "5 months ago",
    "main_left_body_kid_2_kid_2": "4 months ago",
    "main_left_body_kid_3_kid_2": "6 months ago",
    "main_left_body_kid_4_kid_2": "7 months ago",
    "main_left_body_kid_5_kid_2": "8 months ago",
    "main_left_body_kid_6_kid_2": "11 months ago",
    "main_left_body_kid_7_kid_2": "1 months ago",
    "main_left_body_kid_8_kid_2": "1 months ago",
    "main_left_body_kid_9_kid_2": "6 months ago",

    "packages": "Packages",
    "Releases": "Releases",
    "z3_13_0": "z3_13_0",
    "forty_release": "+ 40 releases",

    "reademe": "ReadMe",
    "view_license": "View License",
    "activity": "activity",
    "custom": " Custom properties",
    "stars": "40K stars",
    "watching": "179 watching",
    "forks": "1.5k forks",
    "report_repo": "Report repository",
    "Z3_prover": "Z3 Prover",
    "About": "About",
    "readme_body": "Readme body",
};