#include <vector>
#include <string>
std::vector<std::string> soft_c_names = {
"title",
"wide_main_title",
"title_icons",
"release",
"package",
"main_left_readme",
"main_left_body_kid_0",
"main_left_body_kid_1",
"main_left_body_kid_2",
"main_left_body_kid_3",
"main_left_body_kid_4",
"main_left_body_kid_5",
"main_left_body_kid_6",
"main_left_body_kid_7",
"main_left_body_kid_8",
"main_left_body_kid_9",
"branch_2",
"go_to_file_1",
};

const std::vector<bool> belong_to_right{
true,
false,
true,
true,
true,
true,
false,
true,
true,
true,
};
const std::vector<double> right_bound{
4000.0,
1150.0,
1115.0,
1100.0,
1020.0,
950.0,
870.0,
775.0,
680.0,
530.0,
};
const std::vector<std::vector<std::string>> soft_constraints = {
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
};
