#include <vector>
#include <string>
std::vector<std::string> soft_c_names = {
};

const std::vector<bool> belong_to_right{
true,
false,
true,
true,
true,
true,
false,
true,
true,
true,
};
const std::vector<double> right_bound{
4000.0,
1150.0,
1115.0,
1100.0,
1020.0,
950.0,
870.0,
775.0,
680.0,
530.0,
};
const std::vector<std::vector<std::string>> soft_constraints = {
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_1_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
{
"main_2_feasible",
"branch_2_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_1_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_1_feasible",
"add_icon_2_feasible",
},
{
"main_1_feasible",
"branch_2_feasible",
"go_to_file_2_feasible",
"add_icon_2_feasible",
},
};
