const imageurls = {
    "icon": "images/icon.png",
    "pic": "images/pic.png",
    "rec_tbl_kid_0": "images/p0.png",
    "rec_tbl_kid_1": "images/p1.png",
    "rec_tbl_kid_2": "images/p2.png",
    "rec_tbl_kid_3": "images/p3.png",
    "rec_tbl_kid_4": "images/p4.png",
    "rec_tbl_kid_5": "images/p5.png",
    "rec_tbl_kid_6": "images/p6.png",
    "rec_tbl_kid_7": "images/p7.png",
    "rec_tbl_kid_8": "images/p8.png",
    "rec_tbl_kid_9": "images/p9.png",
    "rec_tbl_kid_10": "images/p10.png",
    "rec_tbl_kid_11": "images/p1.png",
    "rec_tbl_kid_12": "images/p2.png",
    "rec_tbl_kid_13": "images/p3.png",
    "rec_tbl_kid_14": "images/p4.png",
    "rec_tbl_kid_15": "images/p5.png",
    "rec_tbl_kid_16": "images/p6.png",
    "rec_tbl_kid_17": "images/p7.png",
    "rec_tbl_kid_18": "images/p8.png",
    "rec_tbl_kid_19": "images/p9.png",
    "rec_tbl_kid_20": "images/p0.png",
    "rec_tbl_kid_21": "images/p1.png",
    "rec_tbl_kid_22": "images/p10.png",
    "rec_tbl_kid_23": "images/p1.png",
    "rec_tbl_kid_24": "images/p2.png",


    "welcome_kid_3_kid_0": "images/t0.png",
    "welcome_kid_3_kid_1": "images/t1.png",
    "welcome_kid_3_kid_2": "images/t2.png",
    "welcome_kid_3_kid_3": "images/t3.png",
    "welcome_kid_3_kid_4": "images/t4.png",

    "welcome_kid_1_kid_0": "images/p5.png",
    "welcome_kid_1_kid_1": "images/left.png",
    "welcome_kid_1_kid_2": "images/p7.png",
    "welcome_kid_1_kid_3": "images/p8.png",
    "welcome_kid_1_kid_4": "images/p9.png",
    "welcome_kid_1_kid_5": "images/right.png",

    "welcome_kid_2_kid_0": "images/p1.png",
    "welcome_kid_2_kid_1": "images/left.png",
    "welcome_kid_2_kid_2": "images/p3.png",
    "welcome_kid_2_kid_3": "images/p4.png",
    "welcome_kid_2_kid_4": "images/p0.png",
    "welcome_kid_2_kid_5": "images/right.png",

    "welcome_kid_0_kid_0": "images/welcome_kid_0_kid_0.png",
    "welcome_kid_0_kid_1": "images/welcome_kid_0_kid_1.png",
    "welcome_kid_0_kid_2": "images/welcome_kid_0_kid_2.png",


    "side_bar": "images/side_bar.png",
    "search_icon": "images/search_go.png",
    "cart": "images/cart.png",
    "title_top": "images/title_bg.png",

};

const texts = {
    "rec_title": "Recommend",
    "select_kid_0": "SuperMarket",
    "select_kid_1": "Guess",
    "select_kid_2": "AI",
    "select_kid_3": "Furniture",
    "select_kid_4": "Fashion",
    "select_kid_5": "Import",


    "search_buttons_kid_0": "Sport",
    "search_buttons_kid_1": "Shop",
    "search_buttons_kid_2": "Vedio",
    "search_buttons_kid_3": "Paper",
    "search_buttons_kid_4": "Digital",
    "search_buttons_kid_5": "PC",

    "title_top_left_kid_0": "home",
    "title_top_left_kid_1": "email",
    "title_top_left_kid_2": "name",

    "title_top_right_kid_0": "serve",
    "title_top_right_kid_1": "mobile",
    "title_top_right_kid_2": "phone",
    "title_top_right_kid_3": "web",
    "title_top_right_kid_4": "shop",
    "title_top_right_kid_5": "login",
    "title_top_right_kid_6": "purchase",
    "title_top_right_kid_7": "Web",
};