const imageurls = {
  body_item_0_pic: "images/body_0.jpeg",
  body_item_1_pic: "images/body_1.png",
  body_item_2_pic: "images/body_2.png",
  body_item_3_pic: "images/body_3.png",
  body_item_4_pic: "images/body_4.png",
  body_item_5_pic: "images/body_5.jpeg",
  body_item_6_pic: "images/body_6.jpeg",
  body_item_7_pic: "images/body_7.jpeg",
  body_item_8_pic: "images/body_8.jpeg",
  body_item_9_pic: "images/body_9.jpeg",
  body_item_10_pic: "images/body_0.jpeg",
  body_item_11_pic: "images/body_1.png",
  body_item_12_pic: "images/body_2.png",
  body_item_13_pic: "images/body_3.png",
  body_item_14_pic: "images/body_4.png",
  body_item_15_pic: "images/body_5.jpeg",
  body_item_16_pic: "images/body_6.jpeg",
  body_item_17_pic: "images/body_7.jpeg",
  body_item_18_pic: "images/body_8.jpeg",
  body_item_19_pic: "images/body_9.jpeg",
  main_body_pic: "images/body_big_0.png",

  history: "images/history.png",
  game_icon: "images/game_icon.jpg",
  email_icon: "images/email_icon1.png",
  person: "images/user_icon.jpg",
  search_go: "images/search_icon.webp",
  scan_icon: "images/scan_icon.png",
};

const texts = {
  search_bar_kid_1: ["Tab / to search", "16px"],
  title_phone_down_kid_0: ["直播", "18px"],
  title_phone_down_kid_1: ["推荐", "18px"],
  title_phone_down_kid_2: ["热门", "18px"],
  title_phone_down_kid_3: ["动画", "18px"],
  title_phone_down_kid_4: ["影视", "18px"],
  title_phone_down_kid_5: ["奥运", "18px"],
  title_phone_down_kid_6: ["游戏", "18px"],

  title_pad_center_kid_0: ["直播", "20px"],
  title_pad_center_kid_1: ["推荐", "20px"],
  title_pad_center_kid_2: ["热门", "20px"],
  title_pad_center_kid_3: ["动画", "20px"],
  title_pad_center_kid_4: ["影视", "20px"],
  title_pad_center_kid_5: ["奥运", "20px"],
  title_pad_center_kid_6: ["游戏", "20px"],

  login_info: ["登陆", "30px"],
  title_tv_center_kid_0: ["直播", "30px"],
  title_tv_center_kid_1: ["推荐", "30px"],
  title_tv_center_kid_2: ["热门", "30px"],
  title_tv_center_kid_3: ["动画", "30px"],
  title_tv_center_kid_4: ["影视", "30px"],
  title_tv_center_kid_5: ["奥运", "30px"],
  title_tv_center_kid_6: ["游戏", "30px"],

  body_item_0_word: ["华为享界S9及全场景新品发布会 全程回放", "15px"],
  body_item_1_word: ["【全348集】清华大佬终于把Python整理成动画...", "15px"],
  body_item_2_word: [" 动态视频｜高速摄影机下的巴黎 是什么样的？", "15px"],
  body_item_3_word: ["全能S牌人皇教你遛鬼，角色万花筒！", "15px"],
  body_item_4_word: ["硬控5分钟？影视飓风音效挑战！", "15px"],
  body_item_5_word: ["华为 MatePad Pro 12.2 评测：华为平板史上最亮屏幕，但键盘才是本体", "15px"],
  body_item_6_word: ["「趣看发布会」余总带着享界S9来干翻BBA了！", "15px"],
  body_item_7_word: ["5分钟看完享界S9发布会，首发华为全栈黑科技", "15px"],
  body_item_8_word: ["2024年8月份华为全场景新品发布会", "15px"],
  body_item_9_word: ["创造历史！常园夺得中国首枚奥运女子拳击金牌！", "15px"],
  body_item_10_word: ["华为享界S9及全场景新品发布会 全程回放", "15px"],
  body_item_11_word: ["【全348集】清华大佬终于把Python整理成动画...", "15px"],
  body_item_12_word: ["动态视频｜高速摄影机下的巴黎 是什么样的？", "15px"],
  body_item_13_word: ["全能S牌人皇教你遛鬼，角色万花筒！", "15px"],
  body_item_14_word: ["硬控5分钟？影视飓风音效挑战！", "15px"],
  body_item_15_word: ["华为 MatePad Pro 12.2 评测：华为平板史上最亮屏幕，但键盘才是本体", "15px"],
  body_item_16_word: ["「趣看发布会」余总带着享界S9来干翻BBA了！", "15px"],
  body_item_17_word: ["5分钟看完享界S9发布会，首发华为全栈黑科技", "15px"],
  body_item_18_word: ["2024年8月份华为全场景新品发布会", "15px"],
  body_item_19_word: ["创造历史！常园夺得中国首枚奥运女子拳击金牌！", "15px"],
};

const bords = {
  search_bar: "1px",
};
const abs_pos = {
  down_holder: [,],
  mine: ["images/tv_icon.png"],
  home: ["images/home_icon.png"],
  new: ["images/shop_icon.png"],
  shop: ["images/fan_icon.png"],
  add: ["images/add_icon.png"],
  mine_name: [, "我的"],
  home_name: [, "首页"],
  new_name: [, "会员购"],
  shop_name: [, "动态"],
};
