const imageurls = {
    "body_item_0": "images/body_0.jpg",
    "body_item_1": "images/body_1.jpg",
    "body_item_2": "images/body_2.jpg",
    "body_item_3": "images/body_3.jpg",
    "body_item_4": "images/body_4.jpg",
    "body_item_5": "images/body_5.jpg",
    "body_item_6": "images/body_6.jpg",
    "body_item_7": "images/body_7.jpg",
    "body_item_8": "images/body_8.jpg",
    "body_item_9": "images/body_9.jpg",
    "body_item_10": "images/body_0.jpg",
    "body_item_11": "images/body_1.jpg",
    "body_item_12": "images/body_2.jpg",
    "body_item_13": "images/body_3.jpg",
    "body_item_14": "images/body_4.jpg",
    "body_item_15": "images/body_5.jpg",
    "body_item_16": "images/body_6.jpg",
    "body_item_17": "images/body_7.jpg",
    "body_item_18": "images/body_8.jpg",
    "body_item_19": "images/body_9.jpg",
    "body_item_20": "images/body_0.jpg",
    "body_item_21": "images/body_1.jpg",
    "body_item_22": "images/body_2.jpg",
    "body_item_23": "images/body_3.jpg",
    "body_item_24": "images/body_4.jpg",
    "body_item_25": "images/body_5.jpg",
    "main_body_pic": "images/body_9.jpg",

    "side_item_0": "images/side_0.jpg",
    "side_item_1": "images/side_1.jpg",
    "side_item_2": "images/side_2.jpg",
    "side_item_3": "images/side_3.jpg",
    "side_item_4": "images/side_4.jpg",

    // "title_bg": "images/title_bg.png",
    // "title_icon": "images/title_icon.png",

    // "icon_1": "images/icon_1.png",
    // "icon_2": "images/icon_2.png",

    // "submit": "images/submit.png",
    // "title_search_kid_1": "images/title_search_kid_1.png",
    // "title_search_kid_0": "images/title_search_kid_0.png"


};

const texts = {
    // "hot_table_2_kid_0": "Theme",
    // "hot_table_2_kid_1": "Games",
    // "hot_table_2_kid_2": "Society",
    // "hot_table_2_kid_3": "Live",
    // "hot_table_2_kid_4": "Lesson",
    // "hot_table_2_kid_5": "Songs",

    // "hot_table_1_kid_0": "Theme",
    // "hot_table_1_kid_1": "Games",
    // "hot_table_1_kid_2": "Society",
    // "hot_table_1_kid_3": "Live",
    // "hot_table_1_kid_4": "Lesson",
    // "hot_table_1_kid_5": "Songs",
    // "hot_table_1_kid_6": "Theme",
    // "hot_table_1_kid_7": "Games",
    // "hot_table_1_kid_8": "Society",
    // "hot_table_1_kid_9": "Live",
    // "hot_table_1_kid_10": "Lesson",
    // "hot_table_1_kid_11": "Songs",
    // "hot_table_1_kid_12": "Theme",
    // "hot_table_1_kid_13": "Games",
    // "hot_table_1_kid_14": "Society",
    // "hot_table_1_kid_15": "Live",
    // "hot_table_1_kid_16": "Lesson",
    // "hot_table_1_kid_17": "Songs",
};

const white_texts = {
    // "title_button_left_kid_0": "TV",
    // "title_button_left_kid_1": "Radio",
    // "title_button_left_kid_2": "Paper",
    // "title_button_left_kid_3": "News",
    // "title_button_left_kid_4": "Song",
    // "title_button_left_kid_5": "GAME",
    // "title_button_left_kid_6": "LIVE",
    // "title_button_left_kid_7": "COMIC",
    // "title_button_left_kid_8": "PARIS",

    // "title_button_right_kid_0": "TV",
    // "title_button_right_kid_1": "Radio",
    // "title_button_right_kid_2": "Paper",
    // "title_button_right_kid_3": "News",
    // "title_button_right_kid_4": "Song",
    // "title_button_right_kid_5": "GAME",
    // "title_button_right_kid_6": "LIVE",
};